### ISSUE TITLE
Remove extra list items from the readMe

### ISSUE THREAD

**Issue by roshaan005** [SwapnilChand/awesome-tech-stories-#6]
There are extra list items in the numbered lists , I can contribute by removing those 
![Screenshot from 2021-10-02 14-29-49](https://user-images.githubusercontent.com/73021546/135710859-ac44d4a1-1791-42ea-a98a-e04f1fc7b1d3.png)

**Comment by SwapnilChand** [comment]
Nah. That's unnecessary.
Anyways,
Thank you so much for showing interest!
